# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.paginated_gebiedenstadsdelen_list import PaginatedGebiedenstadsdelenList

class TestPaginatedGebiedenstadsdelenList(unittest.TestCase):
    """PaginatedGebiedenstadsdelenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGebiedenstadsdelenList:
        """Test PaginatedGebiedenstadsdelenList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGebiedenstadsdelenList`
        """
        model = PaginatedGebiedenstadsdelenList()
        if include_optional:
            return PaginatedGebiedenstadsdelenList(
                page = gebieden_api_client.models.paginated_gebiedenbouwblokken_list_page.PaginatedGebiedenbouwblokkenList_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links.PaginatedGebiedenbouwblokkenList__links(
                    self = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_self.PaginatedGebiedenbouwblokkenList__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_next.PaginatedGebiedenbouwblokkenList__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_previous.PaginatedGebiedenbouwblokkenList__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = gebieden_api_client.models.paginated_gebiedenstadsdelen_list__embedded.PaginatedGebiedenstadsdelenList__embedded(
                    stadsdelen = [
                        gebieden_api_client.models.gebiedenstadsdelen.Gebiedenstadsdelen(
                            _links = null, 
                            identificatie = '', 
                            volgnummer = -9223372036854775808, 
                            registratiedatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            naam = '', 
                            code = '', 
                            begin_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            eind_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            documentdatum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            documentnummer = '', 
                            ligt_in_gemeente_id = '', 
                            geometrie = gebieden_api_client.models.polygon.Polygon(), )
                        ], )
            )
        else:
            return PaginatedGebiedenstadsdelenList(
        )
        """

    def testPaginatedGebiedenstadsdelenList(self):
        """Test PaginatedGebiedenstadsdelenList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
