# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.gebiedenstedelijkgebiedprojectofbelangen import Gebiedenstedelijkgebiedprojectofbelangen

class TestGebiedenstedelijkgebiedprojectofbelangen(unittest.TestCase):
    """Gebiedenstedelijkgebiedprojectofbelangen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Gebiedenstedelijkgebiedprojectofbelangen:
        """Test Gebiedenstedelijkgebiedprojectofbelangen
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Gebiedenstedelijkgebiedprojectofbelangen`
        """
        model = Gebiedenstedelijkgebiedprojectofbelangen()
        if include_optional:
            return Gebiedenstedelijkgebiedprojectofbelangen(
                links = gebieden_api_client.models.gebieden_stedelijkgebiedprojectofbelangen_links.GebiedenStedelijkgebiedprojectofbelangenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebiedenstedelijkgebiedprojectofbelangen_link.GebiedenstedelijkgebiedprojectofbelangenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                identificatie = '',
                geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(),
                naam = '',
                categorie_code = '',
                categorie_omschrijving = '',
                url = '',
                datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_actueel_tot = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                legenda = ''
            )
        else:
            return Gebiedenstedelijkgebiedprojectofbelangen(
                links = gebieden_api_client.models.gebieden_stedelijkgebiedprojectofbelangen_links.GebiedenStedelijkgebiedprojectofbelangenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebiedenstedelijkgebiedprojectofbelangen_link.GebiedenstedelijkgebiedprojectofbelangenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                identificatie = '',
                geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(),
        )
        """

    def testGebiedenstedelijkgebiedprojectofbelangen(self):
        """Test Gebiedenstedelijkgebiedprojectofbelangen"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
