# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.paginated_gebiedengrootstedelijke_projecten_list_embedded import PaginatedGebiedengrootstedelijkeProjectenListEmbedded

class TestPaginatedGebiedengrootstedelijkeProjectenListEmbedded(unittest.TestCase):
    """PaginatedGebiedengrootstedelijkeProjectenListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGebiedengrootstedelijkeProjectenListEmbedded:
        """Test PaginatedGebiedengrootstedelijkeProjectenListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGebiedengrootstedelijkeProjectenListEmbedded`
        """
        model = PaginatedGebiedengrootstedelijkeProjectenListEmbedded()
        if include_optional:
            return PaginatedGebiedengrootstedelijkeProjectenListEmbedded(
                grootstedelijke_projecten = [
                    gebieden_api_client.models.gebiedengrootstedelijke_projecten.Gebiedengrootstedelijke_projecten(
                        _links = null, 
                        id = -9223372036854775808, 
                        geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(), 
                        naam = '', 
                        type = '', 
                        url = '', 
                        typering = '', 
                        datum = '', 
                        legenda = '', )
                    ]
            )
        else:
            return PaginatedGebiedengrootstedelijkeProjectenListEmbedded(
        )
        """

    def testPaginatedGebiedengrootstedelijkeProjectenListEmbedded(self):
        """Test PaginatedGebiedengrootstedelijkeProjectenListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
