# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.paginated_gebiedenbouwblokken_list_links_self import PaginatedGebiedenbouwblokkenListLinksSelf

class TestPaginatedGebiedenbouwblokkenListLinksSelf(unittest.TestCase):
    """PaginatedGebiedenbouwblokkenListLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGebiedenbouwblokkenListLinksSelf:
        """Test PaginatedGebiedenbouwblokkenListLinksSelf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGebiedenbouwblokkenListLinksSelf`
        """
        model = PaginatedGebiedenbouwblokkenListLinksSelf()
        if include_optional:
            return PaginatedGebiedenbouwblokkenListLinksSelf(
                href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3'
            )
        else:
            return PaginatedGebiedenbouwblokkenListLinksSelf(
        )
        """

    def testPaginatedGebiedenbouwblokkenListLinksSelf(self):
        """Test PaginatedGebiedenbouwblokkenListLinksSelf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
