# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.brk2_gemeentes_raw_identifier import Brk2GemeentesRawIdentifier

class TestBrk2GemeentesRawIdentifier(unittest.TestCase):
    """Brk2GemeentesRawIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Brk2GemeentesRawIdentifier:
        """Test Brk2GemeentesRawIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Brk2GemeentesRawIdentifier`
        """
        model = Brk2GemeentesRawIdentifier()
        if include_optional:
            return Brk2GemeentesRawIdentifier(
                href = '',
                title = '',
                identificatie = ''
            )
        else:
            return Brk2GemeentesRawIdentifier(
                href = '',
                title = '',
                identificatie = '',
        )
        """

    def testBrk2GemeentesRawIdentifier(self):
        """Test Brk2GemeentesRawIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
