# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.gebiedenggpgebieden import Gebiedenggpgebieden

class TestGebiedenggpgebieden(unittest.TestCase):
    """Gebiedenggpgebieden unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Gebiedenggpgebieden:
        """Test Gebiedenggpgebieden
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Gebiedenggpgebieden`
        """
        model = Gebiedenggpgebieden()
        if include_optional:
            return Gebiedenggpgebieden(
                links = gebieden_api_client.models.gebieden_ggpgebieden_links.GebiedenGgpgebiedenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebieden_ggpgebieden_link.GebiedenGgpgebiedenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    ligt_in_stadsdeel = gebieden_api_client.models.gebieden_stadsdelen_link.GebiedenStadsdelenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    bestaat_uit_buurten = [
                        gebieden_api_client.models.gebiedenggpgebieden_bestaat_uit_buurten_m2_m.GebiedenggpgebiedenBestaatUitBuurten_M2M(
                            href = '', 
                            title = '', 
                            identificatie = '', 
                            volgnummer = -9223372036854775808, 
                            begin_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            eind_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                identificatie = '',
                volgnummer = -9223372036854775808,
                registratiedatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                naam = '',
                code = '',
                begin_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                eind_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                documentdatum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                documentnummer = '',
                ligt_in_stadsdeel_id = '',
                geometrie = gebieden_api_client.models.polygon.Polygon()
            )
        else:
            return Gebiedenggpgebieden(
                links = gebieden_api_client.models.gebieden_ggpgebieden_links.GebiedenGgpgebiedenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebieden_ggpgebieden_link.GebiedenGgpgebiedenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    ligt_in_stadsdeel = gebieden_api_client.models.gebieden_stadsdelen_link.GebiedenStadsdelenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    bestaat_uit_buurten = [
                        gebieden_api_client.models.gebiedenggpgebieden_bestaat_uit_buurten_m2_m.GebiedenggpgebiedenBestaatUitBuurten_M2M(
                            href = '', 
                            title = '', 
                            identificatie = '', 
                            volgnummer = -9223372036854775808, 
                            begin_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            eind_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
                identificatie = '',
                volgnummer = -9223372036854775808,
                ligt_in_stadsdeel_id = '',
        )
        """

    def testGebiedenggpgebieden(self):
        """Test Gebiedenggpgebieden"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
