# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.gebiedenstedelijkgebiedprojectofbelangen_link import GebiedenstedelijkgebiedprojectofbelangenLink

class TestGebiedenstedelijkgebiedprojectofbelangenLink(unittest.TestCase):
    """GebiedenstedelijkgebiedprojectofbelangenLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GebiedenstedelijkgebiedprojectofbelangenLink:
        """Test GebiedenstedelijkgebiedprojectofbelangenLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GebiedenstedelijkgebiedprojectofbelangenLink`
        """
        model = GebiedenstedelijkgebiedprojectofbelangenLink()
        if include_optional:
            return GebiedenstedelijkgebiedprojectofbelangenLink(
                href = '',
                title = '',
                identificatie = ''
            )
        else:
            return GebiedenstedelijkgebiedprojectofbelangenLink(
                href = '',
                title = '',
                identificatie = '',
        )
        """

    def testGebiedenstedelijkgebiedprojectofbelangenLink(self):
        """Test GebiedenstedelijkgebiedprojectofbelangenLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
