# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.multi_line_string import MultiLineString

class TestMultiLineString(unittest.TestCase):
    """MultiLineString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiLineString:
        """Test MultiLineString
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiLineString`
        """
        model = MultiLineString()
        if include_optional:
            return MultiLineString(
                type = 'MultiLineString',
                coordinates = [
                    [
                        [
                            1.337
                            ]
                        ]
                    ]
            )
        else:
            return MultiLineString(
        )
        """

    def testMultiLineString(self):
        """Test MultiLineString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
