# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.paginated_gebiedenbouwblokken_list_links import PaginatedGebiedenbouwblokkenListLinks

class TestPaginatedGebiedenbouwblokkenListLinks(unittest.TestCase):
    """PaginatedGebiedenbouwblokkenListLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGebiedenbouwblokkenListLinks:
        """Test PaginatedGebiedenbouwblokkenListLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGebiedenbouwblokkenListLinks`
        """
        model = PaginatedGebiedenbouwblokkenListLinks()
        if include_optional:
            return PaginatedGebiedenbouwblokkenListLinks(
                var_self = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_self.PaginatedGebiedenbouwblokkenList__links_self(
                    href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ),
                next = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_next.PaginatedGebiedenbouwblokkenList__links_next(
                    href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ),
                previous = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_previous.PaginatedGebiedenbouwblokkenList__links_previous(
                    href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', )
            )
        else:
            return PaginatedGebiedenbouwblokkenListLinks(
        )
        """

    def testPaginatedGebiedenbouwblokkenListLinks(self):
        """Test PaginatedGebiedenbouwblokkenListLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
