# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.gebiedenbouwblokken import Gebiedenbouwblokken

class TestGebiedenbouwblokken(unittest.TestCase):
    """Gebiedenbouwblokken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Gebiedenbouwblokken:
        """Test Gebiedenbouwblokken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Gebiedenbouwblokken`
        """
        model = Gebiedenbouwblokken()
        if include_optional:
            return Gebiedenbouwblokken(
                links = gebieden_api_client.models.gebieden_bouwblokken_links.GebiedenBouwblokkenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebieden_bouwblokken_link.GebiedenBouwblokkenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    ligt_in_buurt = gebieden_api_client.models.gebieden_buurten_link.GebiedenBuurtenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), ),
                identificatie = '',
                volgnummer = -9223372036854775808,
                registratiedatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                code = '',
                begin_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                eind_geldigheid = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ligt_in_buurt_id = '',
                geometrie = gebieden_api_client.models.polygon.Polygon()
            )
        else:
            return Gebiedenbouwblokken(
                links = gebieden_api_client.models.gebieden_bouwblokken_links.GebiedenBouwblokkenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebieden_bouwblokken_link.GebiedenBouwblokkenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), 
                    ligt_in_buurt = gebieden_api_client.models.gebieden_buurten_link.GebiedenBuurtenLink(
                        href = '', 
                        title = '', 
                        identificatie = '', 
                        volgnummer = -9223372036854775808, ), ),
                identificatie = '',
                volgnummer = -9223372036854775808,
                ligt_in_buurt_id = '',
        )
        """

    def testGebiedenbouwblokken(self):
        """Test Gebiedenbouwblokken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
