# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.geometry_collection import GeometryCollection

class TestGeometryCollection(unittest.TestCase):
    """GeometryCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeometryCollection:
        """Test GeometryCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeometryCollection`
        """
        model = GeometryCollection()
        if include_optional:
            return GeometryCollection(
                type = 'GeometryCollection',
                geometries = [
                    gebieden_api_client.models.geometry.Geometry(
                        type = 'Point', 
                        coordinates = [
                            1.337
                            ], )
                    ]
            )
        else:
            return GeometryCollection(
                type = 'GeometryCollection',
                geometries = [
                    gebieden_api_client.models.geometry.Geometry(
                        type = 'Point', 
                        coordinates = [
                            1.337
                            ], )
                    ],
        )
        """

    def testGeometryCollection(self):
        """Test GeometryCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
