# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.api.ggwgebieden_api import GgwgebiedenApi


class TestGgwgebiedenApi(unittest.IsolatedAsyncioTestCase):
    """GgwgebiedenApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = GgwgebiedenApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_gebieden_ggwgebieden_list(self) -> None:
        """Test case for gebieden_ggwgebieden_list

        """
        pass

    async def test_gebieden_ggwgebieden_retrieve(self) -> None:
        """Test case for gebieden_ggwgebieden_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
