# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.gebiedengrootstedelijke_projecten import GebiedengrootstedelijkeProjecten

class TestGebiedengrootstedelijkeProjecten(unittest.TestCase):
    """GebiedengrootstedelijkeProjecten unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GebiedengrootstedelijkeProjecten:
        """Test GebiedengrootstedelijkeProjecten
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GebiedengrootstedelijkeProjecten`
        """
        model = GebiedengrootstedelijkeProjecten()
        if include_optional:
            return GebiedengrootstedelijkeProjecten(
                links = gebieden_api_client.models.gebieden_grootstedelijke_projecten_links.GebiedenGrootstedelijkeProjectenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebiedengrootstedelijke_projecten_link.Gebiedengrootstedelijke_projectenLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), ),
                id = -9223372036854775808,
                geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(),
                naam = '',
                type = '',
                url = '',
                typering = '',
                datum = '',
                legenda = ''
            )
        else:
            return GebiedengrootstedelijkeProjecten(
                links = gebieden_api_client.models.gebieden_grootstedelijke_projecten_links.GebiedenGrootstedelijkeProjectenLinks(
                    schema = '', 
                    self = gebieden_api_client.models.gebiedengrootstedelijke_projecten_link.Gebiedengrootstedelijke_projectenLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), ),
                id = -9223372036854775808,
                geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(),
        )
        """

    def testGebiedengrootstedelijkeProjecten(self):
        """Test GebiedengrootstedelijkeProjecten"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
