# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.api.stedelijkgebiedprojectofbelangen_api import StedelijkgebiedprojectofbelangenApi


class TestStedelijkgebiedprojectofbelangenApi(unittest.IsolatedAsyncioTestCase):
    """StedelijkgebiedprojectofbelangenApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = StedelijkgebiedprojectofbelangenApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_gebieden_stedelijkgebiedprojectofbelangen_list(self) -> None:
        """Test case for gebieden_stedelijkgebiedprojectofbelangen_list

        """
        pass

    async def test_gebieden_stedelijkgebiedprojectofbelangen_retrieve(self) -> None:
        """Test case for gebieden_stedelijkgebiedprojectofbelangen_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
