# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gebieden_api_client.models.paginated_gebiedenstedelijkgebiedprojectofbelangen_list import PaginatedGebiedenstedelijkgebiedprojectofbelangenList

class TestPaginatedGebiedenstedelijkgebiedprojectofbelangenList(unittest.TestCase):
    """PaginatedGebiedenstedelijkgebiedprojectofbelangenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedGebiedenstedelijkgebiedprojectofbelangenList:
        """Test PaginatedGebiedenstedelijkgebiedprojectofbelangenList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedGebiedenstedelijkgebiedprojectofbelangenList`
        """
        model = PaginatedGebiedenstedelijkgebiedprojectofbelangenList()
        if include_optional:
            return PaginatedGebiedenstedelijkgebiedprojectofbelangenList(
                page = gebieden_api_client.models.paginated_gebiedenbouwblokken_list_page.PaginatedGebiedenbouwblokkenList_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links.PaginatedGebiedenbouwblokkenList__links(
                    self = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_self.PaginatedGebiedenbouwblokkenList__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_next.PaginatedGebiedenbouwblokkenList__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = gebieden_api_client.models.paginated_gebiedenbouwblokken_list__links_previous.PaginatedGebiedenbouwblokkenList__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = gebieden_api_client.models.paginated_gebiedenstedelijkgebiedprojectofbelangen_list__embedded.PaginatedGebiedenstedelijkgebiedprojectofbelangenList__embedded(
                    stedelijkgebiedprojectofbelangen = [
                        gebieden_api_client.models.gebiedenstedelijkgebiedprojectofbelangen.Gebiedenstedelijkgebiedprojectofbelangen(
                            _links = null, 
                            identificatie = '', 
                            geometrie = gebieden_api_client.models.multi_polygon.MultiPolygon(), 
                            naam = '', 
                            categorie_code = '', 
                            categorie_omschrijving = '', 
                            url = '', 
                            datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            datum_actueel_tot = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            legenda = '', )
                        ], )
            )
        else:
            return PaginatedGebiedenstedelijkgebiedprojectofbelangenList(
        )
        """

    def testPaginatedGebiedenstedelijkgebiedprojectofbelangenList(self):
        """Test PaginatedGebiedenstedelijkgebiedprojectofbelangenList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
