# coding: utf-8

"""
    gebieden

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from gebieden_api_client.models.gebiedenggwgebieden import Gebiedenggwgebieden
from typing import Optional, Set
from typing_extensions import Self

class PaginatedGebiedenggwgebiedenListEmbedded(BaseModel):
    """
    PaginatedGebiedenggwgebiedenListEmbedded
    """ # noqa: E501
    ggwgebieden: Optional[List[Gebiedenggwgebieden]] = None
    __properties: ClassVar[List[str]] = ["ggwgebieden"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginatedGebiedenggwgebiedenListEmbedded from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in ggwgebieden (list)
        _items = []
        if self.ggwgebieden:
            for _item_ggwgebieden in self.ggwgebieden:
                if _item_ggwgebieden:
                    _items.append(_item_ggwgebieden.to_dict())
            _dict['ggwgebieden'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginatedGebiedenggwgebiedenListEmbedded from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ggwgebieden": [Gebiedenggwgebieden.from_dict(_item) for _item in obj["ggwgebieden"]] if obj.get("ggwgebieden") is not None else None
        })
        return _obj


